import Head from 'next/head'
import Feed from '../components/Feed'
import Header from '../components/Header'

export default function Home({ storyData }) {
  console.log(storyData);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* Header */}
        <Header />

        {/* Feed */}
        <Feed storyData={storyData} />

        {/* Modal */}
      </main>
    </div>
  )
}
export async function getStaticProps() {
  const res = await fetch('https://dummyapi.io/data/v1/user?limit=20', {
    method: 'GET',
    headers: {
      'app-id': '6329d8643f0c04bb881d6411'
    }
  });
  const parsed = await res.json();
  return {
    props: {
      storyData: parsed.data
    }
  }
}
